/**
 * PRD §5.3 / §10.1 — Sample Data Registry
 * Provides default datasets for each chart type's data schema.
 */

// Standard chart sample data
export const SAMPLE_DATA: Record<string, Record<string, unknown>[]> = {
  'monthly-revenue': [
    { month: 'Jan', revenue: 4200 },
    { month: 'Feb', revenue: 5100 },
    { month: 'Mar', revenue: 4800 },
    { month: 'Apr', revenue: 6200 },
    { month: 'May', revenue: 5900 },
    { month: 'Jun', revenue: 7100 },
  ],
  'quarterly-comparison': [
    { quarter: 'Q1', current: 12500, previous: 10200 },
    { quarter: 'Q2', current: 14800, previous: 11900 },
    { quarter: 'Q3', current: 16200, previous: 13500 },
    { quarter: 'Q4', current: 18900, previous: 15100 },
  ],
  'category-breakdown': [
    { category: 'Product A', value: 35 },
    { category: 'Product B', value: 28 },
    { category: 'Product C', value: 19 },
    { category: 'Product D', value: 12 },
    { category: 'Other', value: 6 },
  ],
  'scatter-correlation': [
    { x: 10, y: 24, size: 8 },
    { x: 25, y: 45, size: 12 },
    { x: 35, y: 32, size: 6 },
    { x: 50, y: 68, size: 15 },
    { x: 65, y: 55, size: 10 },
    { x: 78, y: 82, size: 20 },
    { x: 90, y: 75, size: 14 },
  ],
  'multi-series': [
    { month: 'Jan', sales: 4200, expenses: 3100, profit: 1100 },
    { month: 'Feb', sales: 5100, expenses: 3400, profit: 1700 },
    { month: 'Mar', sales: 4800, expenses: 3200, profit: 1600 },
    { month: 'Apr', sales: 6200, expenses: 3800, profit: 2400 },
    { month: 'May', sales: 5900, expenses: 3600, profit: 2300 },
    { month: 'Jun', sales: 7100, expenses: 4100, profit: 3000 },
  ],
  'radar-metrics': [
    { metric: 'Speed', value: 85 },
    { metric: 'Reliability', value: 92 },
    { metric: 'Comfort', value: 78 },
    { metric: 'Safety', value: 95 },
    { metric: 'Efficiency', value: 88 },
    { metric: 'Cost', value: 65 },
  ],
  'heatmap-weekly': [
    { day: 'Mon', hour: '9am', value: 12 },
    { day: 'Mon', hour: '12pm', value: 45 },
    { day: 'Mon', hour: '3pm', value: 38 },
    { day: 'Mon', hour: '6pm', value: 22 },
    { day: 'Tue', hour: '9am', value: 18 },
    { day: 'Tue', hour: '12pm', value: 52 },
    { day: 'Tue', hour: '3pm', value: 41 },
    { day: 'Tue', hour: '6pm', value: 15 },
    { day: 'Wed', hour: '9am', value: 25 },
    { day: 'Wed', hour: '12pm', value: 48 },
    { day: 'Wed', hour: '3pm', value: 35 },
    { day: 'Wed', hour: '6pm', value: 28 },
  ],
  'funnel-conversion': [
    { stage: 'Visited', value: 10000 },
    { stage: 'Signed Up', value: 4200 },
    { stage: 'Activated', value: 2800 },
    { stage: 'Subscribed', value: 1200 },
    { stage: 'Retained', value: 850 },
  ],
  'candlestick-stock': [
    { date: '2024-01-02', open: 150.2, high: 155.8, low: 148.5, close: 154.3 },
    { date: '2024-01-03', open: 154.3, high: 158.1, low: 152.0, close: 156.7 },
    { date: '2024-01-04', open: 156.7, high: 157.9, low: 151.2, close: 152.8 },
    { date: '2024-01-05', open: 152.8, high: 159.4, low: 152.0, close: 158.9 },
    { date: '2024-01-08', open: 158.9, high: 162.3, low: 157.5, close: 161.1 },
  ],
  'gauge-single': [
    { label: 'Performance', value: 73, min: 0, max: 100 },
  ],
  'waterfall-pnl': [
    { label: 'Revenue', value: 420000, type: 'positive' },
    { label: 'COGS', value: -180000, type: 'negative' },
    { label: 'Gross Profit', value: 240000, type: 'subtotal' },
    { label: 'Marketing', value: -65000, type: 'negative' },
    { label: 'R&D', value: -85000, type: 'negative' },
    { label: 'Admin', value: -30000, type: 'negative' },
    { label: 'Net Income', value: 60000, type: 'total' },
  ],
};

// Graph sample data (nodes + edges)
export const GRAPH_SAMPLE_DATA: Record<string, { nodes: Record<string, unknown>[]; edges: Record<string, unknown>[] }> = {
  'social-network': {
    nodes: [
      { id: '1', label: 'Alice', group: 'engineering' },
      { id: '2', label: 'Bob', group: 'engineering' },
      { id: '3', label: 'Carol', group: 'design' },
      { id: '4', label: 'Dave', group: 'design' },
      { id: '5', label: 'Eve', group: 'product' },
      { id: '6', label: 'Frank', group: 'product' },
      { id: '7', label: 'Grace', group: 'engineering' },
      { id: '8', label: 'Heidi', group: 'marketing' },
    ],
    edges: [
      { source: '1', target: '2', label: 'WORKS_WITH' },
      { source: '1', target: '3', label: 'COLLABORATES' },
      { source: '2', target: '7', label: 'WORKS_WITH' },
      { source: '3', target: '4', label: 'WORKS_WITH' },
      { source: '3', target: '5', label: 'COLLABORATES' },
      { source: '5', target: '6', label: 'WORKS_WITH' },
      { source: '5', target: '1', label: 'MANAGES' },
      { source: '6', target: '8', label: 'COLLABORATES' },
      { source: '7', target: '4', label: 'COLLABORATES' },
      { source: '8', target: '3', label: 'COLLABORATES' },
    ],
  },
  'knowledge-graph': {
    nodes: [
      { id: 'ml', label: 'Machine Learning', group: 'field' },
      { id: 'dl', label: 'Deep Learning', group: 'field' },
      { id: 'nlp', label: 'NLP', group: 'field' },
      { id: 'cv', label: 'Computer Vision', group: 'field' },
      { id: 'transformer', label: 'Transformer', group: 'architecture' },
      { id: 'cnn', label: 'CNN', group: 'architecture' },
      { id: 'rnn', label: 'RNN', group: 'architecture' },
      { id: 'gpt', label: 'GPT', group: 'model' },
      { id: 'bert', label: 'BERT', group: 'model' },
      { id: 'resnet', label: 'ResNet', group: 'model' },
    ],
    edges: [
      { source: 'dl', target: 'ml', label: 'SUBFIELD_OF' },
      { source: 'nlp', target: 'ml', label: 'SUBFIELD_OF' },
      { source: 'cv', target: 'ml', label: 'SUBFIELD_OF' },
      { source: 'transformer', target: 'dl', label: 'USED_IN' },
      { source: 'cnn', target: 'cv', label: 'USED_IN' },
      { source: 'rnn', target: 'nlp', label: 'USED_IN' },
      { source: 'gpt', target: 'transformer', label: 'BASED_ON' },
      { source: 'bert', target: 'transformer', label: 'BASED_ON' },
      { source: 'resnet', target: 'cnn', label: 'BASED_ON' },
      { source: 'gpt', target: 'nlp', label: 'APPLIED_TO' },
      { source: 'bert', target: 'nlp', label: 'APPLIED_TO' },
      { source: 'resnet', target: 'cv', label: 'APPLIED_TO' },
    ],
  },
  'dependency-tree': {
    nodes: [
      { id: 'app', label: 'App', group: 'root' },
      { id: 'auth', label: 'Auth Service', group: 'service' },
      { id: 'api', label: 'API Gateway', group: 'service' },
      { id: 'db', label: 'Database', group: 'infra' },
      { id: 'cache', label: 'Redis Cache', group: 'infra' },
      { id: 'queue', label: 'Message Queue', group: 'infra' },
      { id: 'worker', label: 'Worker', group: 'service' },
      { id: 'storage', label: 'S3 Storage', group: 'infra' },
    ],
    edges: [
      { source: 'app', target: 'api' },
      { source: 'api', target: 'auth' },
      { source: 'api', target: 'db' },
      { source: 'api', target: 'cache' },
      { source: 'auth', target: 'db' },
      { source: 'auth', target: 'cache' },
      { source: 'api', target: 'queue' },
      { source: 'worker', target: 'queue' },
      { source: 'worker', target: 'db' },
      { source: 'worker', target: 'storage' },
    ],
  },
};
