/**
 * PRD §17.1 — Template Catalog
 * Hand-crafted seed templates + programmatically generated matrix.
 * Total: 300+ templates covering the full type × library × effect matrix.
 */

import type { TemplateMetadata } from '@/types/template';
import { generateTemplateMatrix } from './template-generator';

const HAND_CRAFTED_TEMPLATES: TemplateMetadata[] = [
  {
    id: 'bar-recharts-none-01',
    title: 'Clean Revenue Bars',
    subtitle: 'Minimal bar chart showing monthly revenue',
    chartType: 'bar',
    library: 'recharts',
    palette: 'midnight',
    effect: null,
    effectConfig: null,
    dataKey: 'monthly-revenue',
    dataSchema: 'monthly-single',
    tags: ['comparison', 'revenue'],
    useCases: ['dashboard', 'report'],
    height: 280,
    config: { barSize: 32, radius: [4, 4, 0, 0] },
    renderModule: 'recharts-renderer',
    codeTemplates: { react: 'bar-recharts' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'line-recharts-neon-01',
    title: 'Neon Pulse Line',
    subtitle: 'Glowing line chart with neon effect',
    chartType: 'line',
    library: 'recharts',
    palette: 'neon',
    effect: 'neon-glow',
    effectConfig: { intensity: 80 },
    dataKey: 'monthly-revenue',
    dataSchema: 'monthly-single',
    tags: ['trend', 'revenue'],
    useCases: ['dashboard', 'presentation'],
    height: 260,
    config: { strokeWidth: 3, dot: false },
    renderModule: 'recharts-renderer',
    codeTemplates: { react: 'line-recharts' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'pie-chartjs-glass-01',
    title: 'Glass Donut',
    subtitle: 'Frosted glass donut chart with category breakdown',
    chartType: 'donut',
    library: 'chartjs',
    palette: 'sunset',
    effect: 'glass-morphism',
    effectConfig: { intensity: 60 },
    dataKey: 'category-breakdown',
    dataSchema: 'category-value',
    tags: ['composition', 'breakdown'],
    useCases: ['presentation', 'pitch-deck'],
    height: 320,
    config: { cutout: '65%' },
    renderModule: 'chartjs-renderer',
    codeTemplates: { react: 'pie-chartjs' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'area-d3-gradient-01',
    title: 'Gradient Wave Area',
    subtitle: 'D3 area chart with smooth gradient mesh background',
    chartType: 'area',
    library: 'd3',
    palette: 'ocean',
    effect: 'gradient-mesh',
    effectConfig: { intensity: 45 },
    dataKey: 'monthly-revenue',
    dataSchema: 'monthly-single',
    tags: ['trend', 'flow'],
    useCases: ['editorial', 'report'],
    height: 240,
    config: { curve: 'natural' },
    renderModule: 'd3-renderer',
    codeTemplates: { react: 'area-d3' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'scatter-plotly-particles-01',
    title: 'Cosmic Scatter',
    subtitle: 'Plotly scatter plot with starfield particle background',
    chartType: 'scatter',
    library: 'plotly',
    palette: 'coral',
    effect: 'starfield',
    effectConfig: { intensity: 70 },
    dataKey: 'scatter-correlation',
    dataSchema: 'scatter-xy',
    tags: ['correlation', 'analysis'],
    useCases: ['report', 'editorial'],
    height: 300,
    config: { mode: 'markers', markerSize: 12 },
    renderModule: 'plotly-renderer',
    codeTemplates: { react: 'scatter-plotly' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'radar-nivo-sketch-01',
    title: 'Sketched Radar',
    subtitle: 'Hand-drawn style radar chart for creative presentations',
    chartType: 'radar',
    library: 'nivo',
    palette: 'earth',
    effect: 'hand-drawn-sketch',
    effectConfig: { intensity: 55 },
    dataKey: 'radar-metrics',
    dataSchema: 'radar',
    tags: ['comparison', 'metrics'],
    useCases: ['presentation', 'infographic'],
    height: 340,
    config: {},
    renderModule: 'nivo-renderer',
    codeTemplates: { react: 'radar-nivo' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'bar-echarts-3d-01',
    title: '3D Revenue Bars',
    subtitle: 'ECharts bar chart with 3D perspective tilt',
    chartType: 'bar',
    library: 'echarts',
    palette: 'ember',
    effect: '3d-perspective',
    effectConfig: { intensity: 65 },
    dataKey: 'quarterly-comparison',
    dataSchema: 'quarterly-dual',
    tags: ['comparison', 'quarterly'],
    useCases: ['pitch-deck', 'presentation'],
    height: 300,
    config: {},
    renderModule: 'echarts-renderer',
    codeTemplates: { react: 'bar-echarts' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'candlestick-lc-none-01',
    title: 'Clean Candlestick',
    subtitle: 'Financial candlestick chart with Lightweight Charts',
    chartType: 'candlestick',
    library: 'lightweight-charts',
    palette: 'forest',
    effect: null,
    effectConfig: null,
    dataKey: 'candlestick-stock',
    dataSchema: 'ohlc',
    tags: ['financial', 'stock'],
    useCases: ['dashboard', 'report'],
    height: 280,
    config: {},
    renderModule: 'lightweight-charts-renderer',
    codeTemplates: { react: 'candlestick-lc' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'graph-force-g6-bloom-01',
    title: 'Force Bloom Network',
    subtitle: 'Interactive force-directed graph with bloom effect',
    chartType: 'graph-force',
    library: 'g6',
    palette: 'neon',
    effect: 'force-bloom',
    effectConfig: { intensity: 75 },
    dataKey: 'social-network',
    dataSchema: 'graph-social',
    tags: ['network', 'social', 'interactive'],
    useCases: ['dashboard', 'presentation'],
    height: 380,
    config: {},
    renderModule: 'g6-renderer',
    codeTemplates: { react: 'graph-g6' },
    layoutConfig: { algorithm: 'force', params: { springLength: 150, repulsion: 200 } },
    interactionDefaults: ['zoom-pan', 'node-drag', 'hover-highlight'],
    maxNodes: 500,
    neo4jBoilerplate: false,
  },
  {
    id: 'graph-knowledge-cytoscape-ripple-01',
    title: 'Knowledge Ripple',
    subtitle: 'Knowledge graph with node ripple interactions',
    chartType: 'graph-knowledge',
    library: 'cytoscape',
    palette: 'midnight',
    effect: 'node-ripple',
    effectConfig: { intensity: 60 },
    dataKey: 'knowledge-graph',
    dataSchema: 'graph-knowledge',
    tags: ['knowledge', 'graph', 'interactive'],
    useCases: ['editorial', 'infographic'],
    height: 360,
    config: {},
    renderModule: 'cytoscape-renderer',
    codeTemplates: { react: 'graph-cytoscape' },
    layoutConfig: { algorithm: 'cose', params: { idealEdgeLength: 100 } },
    interactionDefaults: ['zoom-pan', 'node-drag', 'hover-highlight', 'search'],
    maxNodes: 1000,
    neo4jBoilerplate: true,
  },
  {
    id: 'funnel-d3-pulse-01',
    title: 'Pulsing Funnel',
    subtitle: 'Conversion funnel with data pulse animation',
    chartType: 'funnel',
    library: 'd3',
    palette: 'berry',
    effect: 'data-pulse',
    effectConfig: { intensity: 50 },
    dataKey: 'funnel-conversion',
    dataSchema: 'funnel',
    tags: ['conversion', 'marketing'],
    useCases: ['dashboard', 'pitch-deck'],
    height: 320,
    config: {},
    renderModule: 'd3-renderer',
    codeTemplates: { react: 'funnel-d3' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
  {
    id: 'heatmap-nivo-noise-01',
    title: 'Textured Heatmap',
    subtitle: 'Weekly activity heatmap with editorial noise texture',
    chartType: 'heatmap',
    library: 'nivo',
    palette: 'coral',
    effect: 'noise-texture',
    effectConfig: { intensity: 35 },
    dataKey: 'heatmap-weekly',
    dataSchema: 'heatmap',
    tags: ['activity', 'time-series'],
    useCases: ['dashboard', 'report'],
    height: 240,
    config: {},
    renderModule: 'nivo-renderer',
    codeTemplates: { react: 'heatmap-nivo' },
    layoutConfig: null,
    interactionDefaults: [],
    maxNodes: null,
    neo4jBoilerplate: false,
  },
];

// Merge hand-crafted templates with generated matrix
// Hand-crafted ones come first and take priority (by ID dedup)
const generatedTemplates = generateTemplateMatrix({ maxTemplates: 350 });
const handCraftedIds = new Set(HAND_CRAFTED_TEMPLATES.map((t) => t.id));
const uniqueGenerated = generatedTemplates.filter((t) => !handCraftedIds.has(t.id));

export const SEED_TEMPLATES: TemplateMetadata[] = [
  ...HAND_CRAFTED_TEMPLATES,
  ...uniqueGenerated,
];
