/**
 * PRD §13.1 — GET /api/templates/:id/code
 * Generated code for a template in a specific framework.
 * Stub: returns placeholder code.
 */

import { NextRequest, NextResponse } from 'next/server';
import { SEED_TEMPLATES } from '@/lib/seed-templates';
import type { Framework } from '@/types/template';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const template = SEED_TEMPLATES.find((t) => t.id === id);

  if (!template) {
    return NextResponse.json({ error: 'Template not found' }, { status: 404 });
  }

  const searchParams = request.nextUrl.searchParams;
  const framework = (searchParams.get('framework') || 'react') as Framework;
  const includeEffects = searchParams.get('includeEffects') !== 'false';
  const includeTypes = searchParams.get('includeTypes') === 'true';

  // Stub code generation — will be replaced by real code templates in Phase 6
  const ext = { react: 'jsx', vanilla: 'js', vue: 'vue', svelte: 'svelte' }[framework];
  const lang = includeTypes && framework === 'react' ? 'tsx' : ext;

  const code = `// ${template.title}
// Generated by ChartLit — ${framework} component
// Library: ${template.library}
// Effect: ${template.effect || 'none'}

// TODO: Real code generation (Phase 6)
// This is a placeholder stub.

export default function ${template.title.replace(/[^a-zA-Z]/g, '')}() {
  return <div>Chart: ${template.title}</div>;
}
`;

  return NextResponse.json({
    code,
    language: lang,
    dependencies: {
      packages: [
        { name: template.library === 'chartjs' ? 'chart.js' : template.library, version: '^latest', purpose: 'Chart rendering' },
      ],
      installCommand: `npm install ${template.library === 'chartjs' ? 'chart.js' : template.library}`,
      peerDeps: [{ name: 'react', version: '>=18.0', purpose: 'React runtime' }],
      totalSize: '~50 kB gzip',
      devDeps: includeTypes ? [{ name: `@types/${template.library}`, version: '^latest', purpose: 'TypeScript types' }] : [],
    },
  });
}
